# Generated by Django 5.2.2 on 2025-06-05 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_utilisateur_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_competence', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='biographie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='fonctions',
            field=models.TextField(blank=True, help_text='Ex : Dévéloppeur - Designer - Formateur', null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='lien_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='lien_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='lien_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='lien_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='lien_twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nombre_projet',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nombre_recompense',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='competences',
            field=models.ManyToManyField(blank=True, null=True, related_name='profils', to='users.competences'),
        ),
    ]
