# Generated by Django 5.2.2 on 2025-06-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_competences_utilisateur_biographie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competences',
            new_name='Competence',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
