# Generated by Django 5.2.2 on 2025-06-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_competences_competence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='competences',
        ),
        migrations.DeleteModel(
            name='Competence',
        ),
    ]
