# Generated by Django 5.2.2 on 2025-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_utilisateur_competences_delete_competence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_competence', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='competences',
            field=models.ManyToManyField(blank=True, null=True, related_name='profils', to='users.competence'),
        ),
    ]
