# Generated by Django 5.2.2 on 2025-06-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_competence_utilisateur_competences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='profils', to='users.competence'),
        ),
    ]
