# Generated by Django 5.2.2 on 2025-06-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photo_profil/'),
        ),
    ]
