# Generated by Django 5.2.2 on 2026-02-01 00:14

import cloudinary.models
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=cloudinary.models.CloudinaryField(blank=True, default=users.models.default_photo_profil, max_length=255, null=True, verbose_name='photo_profil'),
        ),
    ]
