# Generated by Django 5.2.2 on 2026-02-01 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nombre_projet',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nombre_recompense',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
