# Generated by Django 5.2.2 on 2026-02-01 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_utilisateur_nombre_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nombre_projet',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nombre_recompense',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
