# Generated by Django 5.2.2 on 2026-02-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_utilisateur_nombre_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(default='', max_length=200),
        ),
    ]
