version: "3.9"
services:
  web:
    build:
      context: ./portofolio_backend
      dockerfile: Dockerfile
    command: >
      gunicorn portofolio_backend.wsgi:application --bind 0.0.0.0:8000
    container_name: django_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./portofolio_backend:/app
      - db_data:/app/data

volumes:
  db_data:
