version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./portofolio_backend/Dockerfile
    command: >
      gunicorn portofolio_backend.wsgi:application --bind 0.0.0.0:8000
    container_name: django_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./portofolio_backend:/app
    restart: always

volumes:
  db_data:
