# Generated by Django 5.2.2 on 2025-06-08 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0012_alter_projet_technologie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(help_text='Nom et Prenom du client', max_length=200)),
                ('email_client', models.EmailField(max_length=254)),
                ('numero_client', models.CharField(help_text='numero du client', max_length=30)),
                ('message_client', models.TextField(help_text='message du client')),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('service_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='projets.categorie_projet')),
            ],
        ),
    ]
