# Generated by Django 5.2.2 on 2025-06-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=100)),
                ('image_categorie', models.ImageField(blank=True, null=True, upload_to='projet/image_categorie/')),
                ('description_categorie', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
