# Generated by Django 5.2.2 on 2025-06-06 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_technologie', models.CharField(help_text='nom des technologies/logiciels utilisés', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_projet', models.CharField(max_length=200)),
                ('description_projet', models.TextField(blank=True, null=True)),
                ('lien_projet', models.URLField(blank=True, help_text='lien du projet', null=True)),
                ('image_projet', models.ImageField(blank=True, null=True, upload_to='projet/image_projet/')),
                ('fichier_projet', models.ImageField(blank=True, help_text='chargez le fichier du projet', null=True, upload_to='projet/fichier/')),
                ('date_debut', models.DateField(blank=True, help_text='date de debut du projet', null=True)),
                ('date_fin', models.DateField(blank=True, help_text='date de fin du projet', null=True)),
                ('est_public', models.BooleanField(default=True, help_text='Permettre aux visiteurs de voir le projet')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie_projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='projets.categorie_projet')),
                ('technologie', models.ManyToManyField(blank=True, help_text='technologies/logiciels utilisés', null=True, to='projets.technologie')),
            ],
        ),
    ]
