# Generated by Django 5.2.2 on 2025-06-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_remove_categorie_projet_proprietaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_visuel', models.ImageField(upload_to='projet/visuel/')),
                ('description_visuel', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now=True)),
                ('categorie_visuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visuels', to='projets.categorie_projet')),
            ],
        ),
    ]
