# Generated by Django 5.2.2 on 2025-06-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_visuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='visuel',
            name='titre_visuel',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
