# Generated by Django 5.2.2 on 2025-06-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_visuel_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='titre_projet',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
