# Generated by Django 5.2.2 on 2025-06-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0008_alter_projet_titre_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='titre_projet',
            field=models.CharField(max_length=200),
        ),
    ]
