# Generated by Django 5.2.2 on 2025-06-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0009_alter_projet_titre_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='fichier_projet',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='lien_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='lien_drive',
            field=models.URLField(blank=True, help_text='lien drive du projet', null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='lien_facebook',
            field=models.URLField(blank=True, help_text='lien facebook du projet', null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='lien_github',
            field=models.URLField(blank=True, help_text='lien github du projet', null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='lien_instagram',
            field=models.URLField(blank=True, help_text='lien instagram du projet', null=True),
        ),
    ]
