# Generated by Django 5.2.2 on 2025-06-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0010_remove_projet_fichier_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='lien_projet',
            field=models.URLField(blank=True, help_text='lien du projet (web, mobile)', null=True),
        ),
    ]
