# Generated by Django 5.2.2 on 2025-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0011_projet_lien_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='technologie',
            field=models.ManyToManyField(blank=True, help_text='technologies/logiciels utilisés', to='projets.technologie'),
        ),
    ]
