# Generated by Django 5.2.2 on 2025-06-16 04:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0012_alter_projet_technologie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie_projet',
            name='image_categorie',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='projet/image_categorie/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image_projet',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='projet/image_projet/'),
        ),
        migrations.AlterField(
            model_name='visuel',
            name='image_visuel',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='projet/visuel/'),
        ),
    ]
