# Generated by Django 5.2.2 on 2026-02-01 00:02

import cloudinary.models
import projets.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0015_alter_categorie_projet_image_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie_projet',
            name='image_categorie',
            field=cloudinary.models.CloudinaryField(blank=True, default=projets.models.default_image_projet, max_length=255, null=True, verbose_name='image_categorie'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image_projet',
            field=cloudinary.models.CloudinaryField(blank=True, default=projets.models.default_image_projet, max_length=255, null=True, verbose_name='image_projet'),
        ),
        migrations.AlterField(
            model_name='visuel',
            name='image_visuel',
            field=cloudinary.models.CloudinaryField(default=projets.models.default_image_projet, max_length=255, verbose_name='image_visuel'),
        ),
    ]
